// Generated by gencpp from file cmoon_msgs/point.msg
// DO NOT EDIT!


#ifndef CMOON_MSGS_MESSAGE_POINT_H
#define CMOON_MSGS_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cmoon_msgs
{
template <class ContainerAllocator>
struct point_
{
  typedef point_<ContainerAllocator> Type;

  point_()
    : result()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  point_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::cmoon_msgs::point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmoon_msgs::point_<ContainerAllocator> const> ConstPtr;

}; // struct point_

typedef ::cmoon_msgs::point_<std::allocator<void> > point;

typedef boost::shared_ptr< ::cmoon_msgs::point > pointPtr;
typedef boost::shared_ptr< ::cmoon_msgs::point const> pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cmoon_msgs::point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cmoon_msgs::point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cmoon_msgs::point_<ContainerAllocator1> & lhs, const ::cmoon_msgs::point_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cmoon_msgs::point_<ContainerAllocator1> & lhs, const ::cmoon_msgs::point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cmoon_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cmoon_msgs::point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cmoon_msgs::point_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmoon_msgs::point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmoon_msgs::point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmoon_msgs::point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmoon_msgs::point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cmoon_msgs::point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac77d0373f1087448e62e672b94ba1e5";
  }

  static const char* value(const ::cmoon_msgs::point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac77d0373f108744ULL;
  static const uint64_t static_value2 = 0x8e62e672b94ba1e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::cmoon_msgs::point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cmoon_msgs/point";
  }

  static const char* value(const ::cmoon_msgs::point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cmoon_msgs::point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cmoon_msgs::point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cmoon_msgs::point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmoon_msgs::point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cmoon_msgs::point_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CMOON_MSGS_MESSAGE_POINT_H
