// Generated by gencpp from file cmoon_msgs/wordsRequest.msg
// DO NOT EDIT!


#ifndef CMOON_MSGS_MESSAGE_WORDSREQUEST_H
#define CMOON_MSGS_MESSAGE_WORDSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cmoon_msgs
{
template <class ContainerAllocator>
struct wordsRequest_
{
  typedef wordsRequest_<ContainerAllocator> Type;

  wordsRequest_()
    {
    }
  wordsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::cmoon_msgs::wordsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmoon_msgs::wordsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct wordsRequest_

typedef ::cmoon_msgs::wordsRequest_<std::allocator<void> > wordsRequest;

typedef boost::shared_ptr< ::cmoon_msgs::wordsRequest > wordsRequestPtr;
typedef boost::shared_ptr< ::cmoon_msgs::wordsRequest const> wordsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cmoon_msgs::wordsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cmoon_msgs::wordsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace cmoon_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cmoon_msgs::wordsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cmoon_msgs::wordsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmoon_msgs::wordsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmoon_msgs::wordsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmoon_msgs::wordsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmoon_msgs::wordsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cmoon_msgs::wordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cmoon_msgs::wordsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cmoon_msgs::wordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cmoon_msgs/wordsRequest";
  }

  static const char* value(const ::cmoon_msgs::wordsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cmoon_msgs::wordsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::cmoon_msgs::wordsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cmoon_msgs::wordsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wordsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmoon_msgs::wordsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cmoon_msgs::wordsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CMOON_MSGS_MESSAGE_WORDSREQUEST_H
