// Generated by gencpp from file cmoon_msgs/yoloRequest.msg
// DO NOT EDIT!


#ifndef CMOON_MSGS_MESSAGE_YOLOREQUEST_H
#define CMOON_MSGS_MESSAGE_YOLOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cmoon_msgs
{
template <class ContainerAllocator>
struct yoloRequest_
{
  typedef yoloRequest_<ContainerAllocator> Type;

  yoloRequest_()
    : signal()  {
    }
  yoloRequest_(const ContainerAllocator& _alloc)
    : signal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _signal_type;
  _signal_type signal;





  typedef boost::shared_ptr< ::cmoon_msgs::yoloRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmoon_msgs::yoloRequest_<ContainerAllocator> const> ConstPtr;

}; // struct yoloRequest_

typedef ::cmoon_msgs::yoloRequest_<std::allocator<void> > yoloRequest;

typedef boost::shared_ptr< ::cmoon_msgs::yoloRequest > yoloRequestPtr;
typedef boost::shared_ptr< ::cmoon_msgs::yoloRequest const> yoloRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cmoon_msgs::yoloRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cmoon_msgs::yoloRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cmoon_msgs::yoloRequest_<ContainerAllocator1> & lhs, const ::cmoon_msgs::yoloRequest_<ContainerAllocator2> & rhs)
{
  return lhs.signal == rhs.signal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cmoon_msgs::yoloRequest_<ContainerAllocator1> & lhs, const ::cmoon_msgs::yoloRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cmoon_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cmoon_msgs::yoloRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cmoon_msgs::yoloRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmoon_msgs::yoloRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmoon_msgs::yoloRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmoon_msgs::yoloRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmoon_msgs::yoloRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cmoon_msgs::yoloRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9591b8ace81feee36c93130ad3fe6a19";
  }

  static const char* value(const ::cmoon_msgs::yoloRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9591b8ace81feee3ULL;
  static const uint64_t static_value2 = 0x6c93130ad3fe6a19ULL;
};

template<class ContainerAllocator>
struct DataType< ::cmoon_msgs::yoloRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cmoon_msgs/yoloRequest";
  }

  static const char* value(const ::cmoon_msgs::yoloRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cmoon_msgs::yoloRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string signal\n"
;
  }

  static const char* value(const ::cmoon_msgs::yoloRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cmoon_msgs::yoloRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yoloRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmoon_msgs::yoloRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cmoon_msgs::yoloRequest_<ContainerAllocator>& v)
  {
    s << indent << "signal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CMOON_MSGS_MESSAGE_YOLOREQUEST_H
