// Generated by gencpp from file cmoon_msgs/yoloResponse.msg
// DO NOT EDIT!


#ifndef CMOON_MSGS_MESSAGE_YOLORESPONSE_H
#define CMOON_MSGS_MESSAGE_YOLORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cmoon_msgs
{
template <class ContainerAllocator>
struct yoloResponse_
{
  typedef yoloResponse_<ContainerAllocator> Type;

  yoloResponse_()
    : data()  {
    }
  yoloResponse_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::cmoon_msgs::yoloResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmoon_msgs::yoloResponse_<ContainerAllocator> const> ConstPtr;

}; // struct yoloResponse_

typedef ::cmoon_msgs::yoloResponse_<std::allocator<void> > yoloResponse;

typedef boost::shared_ptr< ::cmoon_msgs::yoloResponse > yoloResponsePtr;
typedef boost::shared_ptr< ::cmoon_msgs::yoloResponse const> yoloResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cmoon_msgs::yoloResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cmoon_msgs::yoloResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cmoon_msgs::yoloResponse_<ContainerAllocator1> & lhs, const ::cmoon_msgs::yoloResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cmoon_msgs::yoloResponse_<ContainerAllocator1> & lhs, const ::cmoon_msgs::yoloResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cmoon_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cmoon_msgs::yoloResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cmoon_msgs::yoloResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmoon_msgs::yoloResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmoon_msgs::yoloResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmoon_msgs::yoloResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmoon_msgs::yoloResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cmoon_msgs::yoloResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::cmoon_msgs::yoloResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992ce8a1687cec8cULL;
  static const uint64_t static_value2 = 0x8bd883ec73ca41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::cmoon_msgs::yoloResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cmoon_msgs/yoloResponse";
  }

  static const char* value(const ::cmoon_msgs::yoloResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cmoon_msgs::yoloResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
;
  }

  static const char* value(const ::cmoon_msgs::yoloResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cmoon_msgs::yoloResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yoloResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmoon_msgs::yoloResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cmoon_msgs::yoloResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CMOON_MSGS_MESSAGE_YOLORESPONSE_H
